name: Update README Automatically

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 4 * * *"  # Tous les jours à 4h du matin UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          pip install requests
          pip install requests openai
          sudo apt-get install -y pandoc texlive-xetex librsvg2-bin fonts-dejavu

      - name: Generate README
        run: |
          python generate_readme.py

      - name: Commit README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'actions@github.com'
          git pull origin main  # Évite les conflits
          git add README.md
          git commit -m "📝 Mise à jour automatique du README" || echo "Pas de changement"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/LC-BONNET/exemple-readme-auto.git main

